-- =====================================================================
--                     IMPORTING CSV DATA WITH \copy
-- =====================================================================

/*
\copy:

- A psql meta-command used to import data from a file into a PostgreSQL table.
- It reads the file from the computer where the psql client is running.
- It is not normal SQL.
- It works inside psql, but usually not inside DataGrip's SQL console.

Basic syntax:

\copy table_name(column1, column2, column3)
FROM 'file_path'
WITH (FORMAT CSV, HEADER);
*/


-- =====================================================================
--                         CREATE THE TABLE
-- =====================================================================

DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(128),
    last_name VARCHAR(128),
    email VARCHAR(128),
    gender VARCHAR(20),
    ip_address VARCHAR(30)
);


/*
GENERATED BY DEFAULT AS IDENTITY:

- PostgreSQL normally generates the ID automatically.
- However, an explicitly provided ID is also allowed.
- This is useful when importing CSV files that already contain IDs.

Compare:

GENERATED ALWAYS AS IDENTITY
    - PostgreSQL generates the ID.
    - Manual IDs are normally rejected.

GENERATED BY DEFAULT AS IDENTITY
    - PostgreSQL generates the ID when no ID is provided.
    - Manual IDs are allowed.
*/


-- =====================================================================
--                         EXAMPLE CSV FILE
-- =====================================================================

/*
MOCK_DATA.csv might contain:

id,first_name,last_name,email,gender,ip_address
1,Zebadiah,Lockie,zlockie0@cnbc.com,Male,180.112.26.232
2,Maria,Smith,msmith@example.com,Female,192.168.1.20
3,John,Doe,jdoe@example.com,Male,10.0.0.15

The first row is the header.
Every following row contains six values.
*/


-- =====================================================================
--                        IMPORT THE CSV FILE
-- =====================================================================

\copy users(id, first_name, last_name, email, gender, ip_address) FROM 'C:/Users/nishc/Downloads/MOCK_DATA.csv' WITH (FORMAT CSV, HEADER);


/*
Meaning:

\copy
    - psql command that imports data.

users(...)
    - Destination table and the exact column order.

FROM 'C:/Users/nishc/Downloads/MOCK_DATA.csv'
    - Path to the CSV file on the client computer.

FORMAT CSV
    - Tells PostgreSQL to parse the file as CSV.

HEADER
    - Tells PostgreSQL to skip the first row because it contains column names.
*/


-- =====================================================================
--                        VERIFY THE IMPORT
-- =====================================================================

SELECT *
FROM users
LIMIT 10;


-- Count all imported rows.

SELECT COUNT(*)
FROM users;


-- View selected columns.

SELECT
    id,
    first_name,
    last_name,
    email
FROM users
LIMIT 20;


-- =====================================================================
--                         IMPORTANT: ONE LINE
-- =====================================================================

/*
\copy must be entered as one complete psql command.

Correct:

\copy users(id, first_name, last_name, email, gender, ip_address) FROM 'C:/Users/nishc/Downloads/MOCK_DATA.csv' WITH (FORMAT CSV, HEADER);

Wrong:

\copy users(id, first_name, last_name, email, gender, ip_address)

FROM 'C:/Users/nishc/Downloads/MOCK_DATA.csv'
WITH (FORMAT CSV, HEADER);

Why?

\copy is a psql meta-command, not a normal SQL statement.
psql expects the complete meta-command on the same line.
*/


-- =====================================================================
--                      UNDERSTANDING PSQL PROMPTS
-- =====================================================================

/*
postgres=#

    - psql is ready for a new command.

postgres-#

    - psql thinks a normal SQL command is incomplete.
    - It is waiting for more input.

postgres(#

    - psql is waiting for a closing parenthesis.

If stuck inside an unfinished command:

Press:

Ctrl + C

This cancels the current input and returns to:

postgres=#
*/


-- =====================================================================
--                      COMMON ERROR: WRONG TABLE
-- =====================================================================

/*
Error:

relation "track_raw" does not exist

Cause:

The \copy command tried to import into a table named track_raw,
but that table was never created.

Wrong:

\copy track_raw(...)

Correct:

\copy users(...)
*/


-- =====================================================================
--                   COMMON ERROR: EXTRA CSV COLUMN
-- =====================================================================

/*
Error:

extra data after last expected column

Example CSV row:

1,Zebadiah,Lockie,zlockie0@cnbc.com,Male,180.112.26.232

This row contains six values:

1. id
2. first_name
3. last_name
4. email
5. gender
6. ip_address

But this command expects only five:

\copy users(first_name, last_name, email, gender, ip_address) ...

Therefore, PostgreSQL sees one extra value.

Fix:

Include id in the column list:

\copy users(id, first_name, last_name, email, gender, ip_address) ...
*/


-- =====================================================================
--                IMPORT WITHOUT THE ID COLUMN
-- =====================================================================


--     just generate a file from MOCKAROO

--     GOTO - https://www.mockaroo.com/
/*
When the CSV does not contain IDs, let PostgreSQL generate them.

Example CSV:

first_name,last_name,email,gender,ip_address
Zebadiah,Lockie,zlockie0@cnbc.com,Male,180.112.26.232
Maria,Smith,msmith@example.com,Female,192.168.1.20
*/


-- Use this only when the CSV contains five columns and no ID:

\copy users(first_name, last_name, email, gender, ip_address) FROM 'C:/Users/nishc/Downloads/MOCK_DATA_WITHOUT_ID.csv' WITH (FORMAT CSV, HEADER);


/*
Because id is omitted, PostgreSQL generates it automatically.
*/


-- =====================================================================
--                     COMMON ERROR: TYPO
-- =====================================================================

/*
Wrong:

WITH DELIMER ',' CSV

Correct spelling:

DELIMITER

Modern preferred syntax:

WITH (FORMAT CSV, DELIMITER ',', HEADER)

Because comma is already the default CSV delimiter,
this is usually enough:

WITH (FORMAT CSV, HEADER)
*/


-- =====================================================================
--                        WINDOWS FILE PATHS
-- =====================================================================

/*
Prefer forward slashes:

'C:/Users/nishc/Downloads/MOCK_DATA.csv'

This is safer and easier than:

'C:\Users\nishc\Downloads\MOCK_DATA.csv'
*/


-- =====================================================================
--                        HEADER VS NO HEADER
-- =====================================================================

/*
Use HEADER when the first CSV row contains column names.

Example:

id,first_name,last_name,email,gender,ip_address
1,John,Doe,john@example.com,Male,127.0.0.1

Command:

WITH (FORMAT CSV, HEADER)


Do not use HEADER when the file begins immediately with data.

Example:

1,John,Doe,john@example.com,Male,127.0.0.1
2,Maria,Smith,maria@example.com,Female,127.0.0.2

Command:

WITH (FORMAT CSV)
*/


-- =====================================================================
--                     COLUMN ORDER MUST MATCH
-- =====================================================================

/*
The order inside \copy must match the order of values in the CSV.

CSV order:

id,first_name,last_name,email,gender,ip_address

Correct:

\copy users(id, first_name, last_name, email, gender, ip_address) ...

Wrong:

\copy users(email, first_name, last_name, gender, ip_address, id) ...

PostgreSQL follows the provided order exactly.
*/


-- =====================================================================
--                     IDENTITY SEQUENCE AFTER IMPORT
-- =====================================================================

/*
Important:

When manually importing IDs, the identity sequence may not automatically
move to the highest imported ID.

Example:

CSV imported IDs:

1
2
3
...
1000

The sequence may still think the next ID is 1.

Then a later insert without an ID could cause a duplicate-key error.
*/


-- Synchronize the identity sequence with the highest existing ID.

SELECT setval(
    pg_get_serial_sequence('users', 'id'),
    COALESCE((SELECT MAX(id) FROM users), 1),
    true
);


/*
After synchronization, the next generated ID will be greater than MAX(id).
*/


-- Test automatic ID generation after importing.

INSERT INTO users (
    first_name,
    last_name,
    email,
    gender,
    ip_address
)
VALUES (
    'Generated',
    'User',
    'generated@example.com',
    'Other',
    '127.0.0.1'
)
RETURNING *;


-- =====================================================================
--                        \copy VS COPY
-- =====================================================================

/*
\copy:

- psql client command.
- Reads the file from your local/client computer.
- Usually easier for local files.
- Does not require the PostgreSQL server process to access your file path.

COPY:

- PostgreSQL server-side SQL command.
- Reads the file from the database server's filesystem.
- The PostgreSQL server must have permission to access the file.
- Often requires elevated database privileges.

Local Windows file:

    Use \copy.

File physically stored on the database server:

    COPY may be appropriate.
*/


-- Server-side example:

-- COPY users(id, first_name, last_name, email, gender, ip_address)
-- FROM '/server/path/MOCK_DATA.csv'
-- WITH (FORMAT CSV, HEADER);


-- =====================================================================
--                           FINAL SUMMARY
-- =====================================================================

/*
\copy imports a local CSV file through psql.

Main rules:

1. The destination table must already exist.
2. The table name must be correct.
3. The CSV column count must match the \copy column count.
4. The column order must match the CSV order.
5. Use HEADER when the first row contains column names.
6. On Windows, prefer forward slashes in file paths.
7. Enter the entire \copy command on one line.
8. If importing manual identity IDs, synchronize the sequence afterward.
*/


-- Final working command:

\copy users(id, first_name, last_name, email, gender, ip_address) FROM 'C:/Users/nishc/Downloads/MOCK_DATA.csv' WITH (FORMAT CSV, HEADER);